import { Component } from '@angular/core';
import { Player } from '../../../shared/models/player.model';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-team-detail',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './team-detail.component.html',
  styleUrl: './team-detail.component.css'
})
export class TeamDetailComponent {
jugadores: Player[] = [{
  name:'César Marvin Alexander Marroquin Moreira',
  numb: 1,
  points: 0,
  points3: 0,
  assists: 0,
  rebounds: 0,
  blocks: 0,
  steals: 0,
  lost: 0,
},{
  name:'Fredy Alexander Díaz Cutzal ',
  numb: 2,
  points: 0,
  points3: 0,
  assists: 0,
  rebounds: 0,
  blocks: 0,
  steals: 0,
  lost: 0,
},{
  name:'Juan Carlos Galindo Román',
  numb: 3,
  points: 0,
  points3: 0,
  assists: 0,
  rebounds: 0,
  blocks: 0,
  steals: 0,
  lost: 0,
},{
  name:'Marvin Orlando Marroquin Juárez',
  numb: 4,
  points: 0,
  points3: 0,
  assists: 0,
  rebounds: 0,
  blocks: 0,
  steals: 0,
  lost: 0,
},{
  name:'Luis David Vielman Cáceres',
  numb: 5,
  points: 0,
  points3: 0,
  assists: 0,
  rebounds: 0,
  blocks: 0,
  steals: 0,
  lost: 0,
},{
  name:'Gerber Israel Pinzón Siquinajay',
  numb: 6,
  points: 0,
  points3: 0,
  assists: 0,
  rebounds: 0,
  blocks: 0,
  steals: 0,
  lost: 0,
},{
  name:'José Luis Pinzón de León',
  numb: 7,
  points: 0,
  points3: 0,
  assists: 0,
  rebounds: 0,
  blocks: 0,
  steals: 0,
  lost: 0,
},{
  name:'Alexander Héctor Iván Pinzón Higueros',
  numb: 8,
  points: 0,
  points3: 0,
  assists: 0,
  rebounds: 0,
  blocks: 0,
  steals: 0,
  lost: 0,
},{
  name:'Silvestre Rafael Arenales Pinzón ',
  numb: 9,
  points: 0,
  points3: 0,
  assists: 0,
  rebounds: 0,
  blocks: 0,
  steals: 0,
  lost: 0,
},{
  name:'Sergio Geovanny Blanco Noriega ',
  numb: 10,
  points: 0,
  points3: 0,
  assists: 0,
  rebounds: 0,
  blocks: 0,
  steals: 0,
  lost: 0,}]
}
