import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Team } from '../../../shared/models/team.model';

@Component({
  selector: 'app-position-table',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './position-table.component.html',
  styleUrl: './position-table.component.css'
})
export class PositionTableComponent {
  equipos: Team[] = [
    {
      id: '1',
      name: '3K',
      image: '',
      games: 0,
      wins: 0,
      losses: 0,
      lossesdef: 0,
      points: 0,
      pointsf: 0,
      pointsc: 0,
      difference: 0,
    },{
      id: '2',
      name: 'ABT',
      image: '',
      games: 0,
      wins: 0,
      losses: 0,
      lossesdef: 0,
      points: 0,
      pointsf: 0,
      pointsc: 0,
      difference: 0,
    },{
      id: '3',
      name: 'ASTROS',
      image: '',
      games: 0,
      wins: 0,
      losses: 0,
      lossesdef: 0,
      points: 0,
      pointsf: 0,
      pointsc: 0,
      difference: 0,
    },{
      id: '4',
      name: 'BULLS',
      image: '',
      games: 0,
      wins: 0,
      losses: 0,
      lossesdef: 0,
      points: 0,
      pointsf: 0,
      pointsc: 0,
      difference: 0,
    },{
      id: '5',
      name: 'EMUA',
      image: '',
      games: 0,
      wins: 0,
      losses: 0,
      lossesdef: 0,
      points: 0,
      pointsf: 0,
      pointsc: 0,
      difference: 0,
    },{
      id: '6',
      name: 'HAWKS',
      image: '',
      games: 0,
      wins: 0,
      losses: 0,
      lossesdef: 0,
      points: 0,
      pointsf: 0,
      pointsc: 0,
      difference: 0,
    },{
      id: '7',
      name: 'INDIOS',
      image: '',
      games: 0,
      wins: 0,
      losses: 0,
      lossesdef: 0,
      points: 0,
      pointsf: 0,
      pointsc: 0,
      difference: 0,
    },{
      id: '8',
      name: 'MAXI TECPÁN',
      image: '',
      games: 0,
      wins: 0,
      losses: 0,
      lossesdef: 0,
      points: 0,
      pointsf: 0,
      pointsc: 0,
      difference: 0,
    },{
      id: '9',
      name: 'TALENTO DE BARRIO',
      image: '',
      games: 0,
      wins: 0,
      losses: 0,
      lossesdef: 0,
      points: 0,
      pointsf: 0,
      pointsc: 0,
      difference: 0,
    },{
      id: '10',
      name: 'TALENTO JR',
      image: '',
      games: 0,
      wins: 0,
      losses: 0,
      lossesdef: 0,
      points: 0,
      pointsf: 0,
      pointsc: 0,
      difference: 0,
    },{
      id: '11',
      name: 'THUNDER',
      image: '',
      games: 0,
      wins: 0,
      losses: 0,
      lossesdef: 0,
      points: 0,
      pointsf: 0,
      pointsc: 0,
      difference: 0,
    },{
      id: '12',
      name: 'VAGOS',
      image: '',
      games: 0,
      wins: 0,
      losses: 0,
      lossesdef: 0,
      points: 0,
      pointsf: 0,
      pointsc: 0,
      difference: 0,
    },{
      id: '13',
      name: 'WOLFS',
      image: '',
      games: 0,
      wins: 0,
      losses: 0,
      lossesdef: 0,
      points: 0,
      pointsf: 0,
      pointsc: 0,
      difference: 0,
    }
  ]
}
